require:
  - rubocop-sequel
  - rubocop-rake
  - rubocop-minitest

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Rake/Desc:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
