require:
  - rubocop-sequel
  - rubocop-rake

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Rake/Desc:
  Enabled: false

Naming/PredicateName:
  Enabled: false
