# fly.toml file generated for rating-importer on 2023-04-08T19:58:57+02:00

app = "rating-importer"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "waw"
processes = []

[env]

[experimental]
  auto_rollback = true

[processes]
  cron = "supercronic /app/crontab"
