# fly.toml app configuration file generated for rating-importer on 2023-05-28T17:29:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rating-importer"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "waw"

[processes]
  cron = "supercronic /app/crontab"
