name: Base rosters for IDs 80001+

on:
  schedule:
    - cron: '0 7 * * FRI'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Run scraper
      run: bundle exec rake base_rosters:fetch_id_range[80001]
      env:
        CONNECTION_STRING: ${{ secrets.SIMPLE_SCRAPER_CONNECTION_STRING }}
