name: Base rosters for teams in rating tournaments

on:
   schedule:
     - cron: '35 12 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Run scraper
      run: bundle exec rake base_rosters:fetch_for_teams_in_rating_tournaments
      env:
        CONNECTION_STRING: ${{ secrets.SIMPLE_SCRAPER_CONNECTION_STRING }}
