name: Base rosters by ID buckets

on:
  schedule:
    - cron: '0 3 * * WED'

concurrency: base_rosters

jobs:
  import_base_rosters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Run scraper
      run: bundle exec rake base_rosters:fetch_id_range[${{ matrix.min_id }},20000]
      env:
        CONNECTION_STRING: ${{ secrets.SIMPLE_SCRAPER_CONNECTION_STRING }}
