name: CI

on: push

jobs:
  test:
    env:
      RUBY_ENV: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Tests
        run: bundle exec rake test
      - name: Linter
        run: bundle exec rubocop
