name: Tournament details for rating tournaments

on:
  schedule:
    - cron: '50 */6 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Fetch all rating tournaments
        run: bundle exec rake tournaments:details_for_rating_tournaments
        env:
          CONNECTION_STRING: ${{ secrets.SIMPLE_SCRAPER_CONNECTION_STRING }}

      - name: Fetch all recent and future tournaments
        run: bundle exec rake tournaments:details_for_recent_tournaments
        env:
          CONNECTION_STRING: ${{ secrets.SIMPLE_SCRAPER_CONNECTION_STRING }}
